@startuml Insights Storage Broker
participant puptoo
entity platform_inventory_host_ingress
participant HBI
entity platform_inventory_host_egress
participant storage_broker
entity platform_upload_available
puptoo->platform_inventory_host_ingress: puptoo sends successful payload to HBI
platform_inventory_host_ingress->HBI
HBI->platform_inventory_host_egress: HBI advertises new payload to the host-egress topic
platform_inventory_host_egress->storage_broker: Storage Broker reads the egress topic
storage_broker->platform_upload_available: Storage Broker republishes the message to the available topic
Note right of storage_broker: This supports the legacy pipeline
@enduml